### ISSUE TITLE
Compatibility with Origins update

### ISSUE THREAD

**Issue by webmaster442** [zencq/NomNom#10]
When can we expect a version, that's compatible with the Origins update save files?

**Comment by ProfYakkington** [comment]
Think you Question is answered on the Patreon-page (https://www.patreon.com/cengelha ) just look there for updates (dev. steps don´t require being a patreon :
"Origins will be included in alpha.8 and should be there short after [n]ecessary modding tools are updated."
Would bet one of the necessary tools is the mbincompiler ( https://github.com/monkeyman192/MBINCompiler/ )

**Comment by cengelha** [comment]
That's right and I just edited the Patreon page as there is actually one blocker that I found after posting it. I will release alpha.7 tomorrow that already contains the fix for that.

Yes, it's the MBINCompiler I'm waiting for. It got a big update today but still isn't complete. But if we are lucky it could be tomorrow and alpha.8 released by the end of the week.
