### ISSUE TITLE
[Bug] selecting steam save directory

### ISSUE THREAD

**Issue by Mistic92** [zencq/NomNom#179]
### Reproduce
1. Xbox save location was detected, steam no
2. Add C:\Users\XXXXXX\AppData\Roaming\HelloGames\NMS through file->open

### Expected Behavior
add steam

### Files
To make it easier to reproduce your problem it can be helpful to attach your save folder.
Please also attach the crash report (if any) and your log file.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version:  4.70.2.41-beta.11+363b6488df50cc47d957b37a1d99b612623fac49
 - Platform: Xbox + steam
[report.20240718135039.zip](https://github.com/user-attachments/files/16284269/report.20240718135039.zip)

**Comment by leeterry** [comment]
I also have this issue and I am not using Xbox (so it finds no saves at all). Every time I put a text field into the box in the settings asking where saves are located it reverts/deletes it. Every time I try to locate it manually with explorer nothing happens. I tried running as admin and non admin with same results. Not sure if it is because I have a space/_ in my name on Windows, becasue I still use win 10, or something else altogether. I will move it all to the base drive for testing and I will report back if it fixes the issue but not gonna bother if nothing changes.
