### ISSUE TITLE
[Bug] Archived tech packages gone from the inventory after editing the save

### ISSUE THREAD

**Issue by roie-r** [zencq/NomNom#210]
The editor doesn't handle archived tech package. Editing anything at all then saving cause archived tech to be deleted from the inventory when loading the game.
I _think_ it's something about how arch-tech is represented as hex string that should remain so and not converted to utf8.

**Comment by Rogue-Demon-King** [comment]
Same thing happened to me when editing a Manual save a few days ago.

**Comment by Lupox-One** [comment]
I have the same Problem when editing a Save, today with version 5.10.1 and about a week  ago with 5.002.46 beta

**Comment by ckingdev** [comment]
Can confirm that this is still occurring as of The Cursed update. Consistently reproducible with exosuit, starship, and freighter inventories. Fatal errors occur a significant portion of the time when attempting to view the details of packaged tech.

@cengelha 

I understand the difficulties of maintaining a hobby project as a volunteer. I'm not going to make demands about getting this fixed or anything, but while there's a burden on the user to make their own backups and use this at their own risk, given the issues that prevent editing backups within NomNom without destroying them and the destructive, silent nature of this bug, **I think there needs to be a prominent warning about the issue added to the readme until it is resolved.** I see that this has been added to a milestone that has a very loose date at the end of the year, so I know it's on your radar, but I think a readme warning being added asap is a reasonable ask. Users can work around the issue in the meantime by having any important tech installed somewhere, but they need to know that workaround is necessary.

The deletion of packaged tech happens without any notification to the user, and since it happens in all inventories whether they're actively edited or in an unselected exocraft or starship, it's very easy for the problem to go unnoticed for a long while. At that point, even users who did their due diligence and made their own backups are put in the position of choosing between restoring and losing all playtime after the bug occurred, or not restoring and losing items that could represent dozens to hundreds of hours of time spent acquiring them. 

I'm more than happy to attach any logs or write up repro instructions for anything mentioned here, just let me know what would be useful.

Thanks for your work on the project!

**Comment by cengelha** [comment]
@ckingdev Thanks for your feedback.

I actually looked into this over the last days! I found where and why exactly it happens (confirmed my hunch) and I'm currently looking for/working on a solution, so hopefully I can make a 5.20.1 very soon that finally fixes it.

But ofc you are right, this is a bug that should have been mentioned more prominent than here, as data loss may occur.
