### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by DartPower** [zencq/NomNom#37]
Where is Source Code? GPLv3 but nothing in this repo...

**Comment by cengelha** [comment]
As mentioned at the top of the [README](https://github.com/cengelha/NomNom/blob/master/README.md):

> Source code will be available with the first stable release.

**Comment by DartPower** [comment]
>Source code will be available with the first stable release.
Why propriatary now? Where the source code?

**Comment by cengelha** [comment]
It's still planned, no worry ;) Currently working on a big update and when it will be released, I'll upload the source code as well

**Comment by cengelha** [comment]
PS: I "closed this as not planned" because it's a dublicate of #4. Was just a little cleanup, giving it the corrent close state.

**Comment by Troughy** [comment]
My man, I appreciate you working on a tool like this, but I personally don't use/trust any closed-source software (other than games). Also, this is GitHub, meant to share source code, not binaries.

**Comment by cengelha** [comment]
@Troughy I know that GitHub isn't meant to share only binaries :) At least I'm not putting them in the repo/files itself xD

No body forces you to use it, but I understand what you are saying.
Nonetheless, I'm not changing what I mentioned before except that I'll start with it when I have the first public beta ready (and not with the final release). Parts that I outsourced into separate libs are available [here](https://github.com/zencq/libNOM.io), [here](https://github.com/zencq/libNOM.map), and [here](https://github.com/zencq/libNOM.collect) though, as you my know.

Unfortunately, it came to a stop the last two months due to RL stuff and therefore limited time to work on it but think/hope that this first one will be ready relatively soon now.
